name: Discord livery announcement

on:
  push:
    paths:
      - livery.json

jobs:
  discord-livery-announcement:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            commit.txt
            livery.json
            .
          sparse-checkout-cone-mode: false  # disable cone mode for wildcard support
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r .webhook/requirements.txt

      - name: Send webhook
        env:
          LIVERY_UPDATE_WEBHOOK: ${{ secrets.LIVERY_UPDATE_WEBHOOK }}
        run: python3 .webhook/livery_update.py
      
      - name: Commit the file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git add ./.webhookcommit.txt
          git commit -m "Update .webhook/commit.txt"
          git push